mysql_root_password: "super secret root password"
mysql_databases:
  - name: "appDbName"
mysql_users:
  - name: "appDbUser"
    password: "super secet user password"
    priv: "appDbName.*:ALL"

nginx_yum_repo_enabled: true
nginx_vhosts:
  - listen: "80"
    server_name: "app.local"
    root: "{{ web_root }}"
    index: "index.php index.html index.htm"
    state: "present"
    filename: "app.local.conf"
    extra_parameters: |
        location ~ \.php$ {
            include fastcgi_params;
            fastcgi_pass 127.0.0.1:9000;
            fastcgi_index app.php;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            try_files $uri =404;
        }
        location /phpMyAdmin {
            root {{ phpMyAdmin_dest }};
            index index.php index.html index.htm;
            location ~ \.php$ {
                try_files $uri =404;
                fastcgi_pass 127.0.0.1:9000;
                fastcgi_index index.php;
                fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
                include fastcgi_params;
            }
        }

php_webserver_daemon: "nginx"
php_enablerepo: "remi-php71,epel"
php_packages_state: "latest"
php_enable_php_fpm: true
php_packages:
  - php
  - php-common
  - php-fpm
  - php-opcache
  - php-cli
  - php-mysql
  - php-gd
  - php-mbstring
  - php-mcrypt
  - php-pdo
  - php-pear
  - php-xml
  - php-apcu
  - php-pecl-apcu
  - phpmyadmin